export enum OperationType {
  CLEARING = 'CLEARING',
  NURSERY = 'NURSERY',
  PLANTING = 'PLANTING',
  FERTILIZATION = 'FERTILIZATION',
  WEEDING = 'WEEDING',
  PEST_CONTROL = 'PEST_CONTROL',
  HARVEST = 'HARVEST',
  OTHER = 'OTHER',
}
