export enum OperationType {
  CLEARING = 'CLEARING',
  SEED_TREATMENT = 'SEED_TREATMENT',
  NURSERY = 'NURSERY',
  TRANSPLANTING = 'TRANSPLANTING',
  PLANTING = 'PLANTING',
  FERTILIZATION = 'FERTILIZATION',
  WEEDING = 'WEEDING',
  THINNING = 'THINNING',
  EARTHING_UP = 'EARTHING_UP',
  PEST_CONTROL = 'PEST_CONTROL',
  HARVEST = 'HARVEST',
  OTHER = 'OTHER',
}
