export enum PestType {
  INSECT = 'INSECT',
  MITE = 'MITE',
  NEMATODE = 'NEMATODE',
  MOLLUSC = 'MOLLUSC',
  BIRD = 'BIRD',
  MAMMAL = 'MAMMAL',
  ANNUAL_GRASS = 'ANNUAL_GRASS',
  PERENNIAL_GRASS = 'PERENNIAL_GRASS',
  ANNUAL_BROADLEAF = 'ANNUAL_BROADLEAF',
  PERENNIAL_BROADLEAF = 'PERENNIAL_BROADLEAF',
  SEDGE = 'SEDGE',
  OTHER = 'OTHER',
}
