export enum CycleType {
  SEASONAL_ANNUAL = 'SEASONAL_ANNUAL',
  BIENNIAL = 'BIENNIAL',
  PERENNIAL_HERBACEOUS = 'PERENNIAL_HERBACEOUS',
  PERENNIAL_WOODY_FRUIT = 'PERENNIAL_WOODY_FRUIT',
  FORESTRY_WOOD = 'FORESTRY_WOOD',
}
